eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservice:
  second-service:
    endpoints:
      endpoint:
        uri: http://SECOND-SERVICE/consumer/details
  first-service:
    endpoints:
      endpoint:
        uri: http://FIRST-SERVICE/employee      

message:
  info: Hello, World! This Config Server Testing.....
