eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates: 
          - Path=/order/**
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payment/**

    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/info

message:
  info: Hello, World! This Config Server Testing.....with Microservices......
  data: This is testing of the centralized config server
